# -*- mode: ansible -*-
- name: Rename from orangepizero2w or radxa-zero3 to jkt-rv-ha
  hosts: bare
  become: true
  tasks:
    - include_tasks: tasks/threads-max.yml # noqa: fqcn[action-core] name[missing]
    - name: Set hostname
      ansible.builtin.hostname:
        name: jkt-rv-ha
        use: debian
    - name: Set hosts
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: orangepizero2w|radxa-zero3
        replace: jkt-rv-ha
    - include_tasks: tasks/%sudo.yml # noqa: fqcn[action-core] name[missing]
- name: Update overlays on radxa-zero3
  hosts:
    - radxa-zero3
  become: true
  tasks:
    - include_tasks: tasks/armbianEnv-overlay.yml # noqa: fqcn[action-core] name[missing]
- name: Reboot orangepizero2w or radxa-zero3
  hosts:
    - orangepizero2w
    - radxa-zero3
  become: true
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        pre_reboot_delay: 10
