# -*- mode: ansible -*-
# see debian-stretch.md
- name: Install gattacker
  hosts: gattacker
  become: true
  tasks:
    - include_tasks: tasks/vars+packages.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/editor.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/apt_upgrade.yml # noqa: fqcn[action-core] name[missing]
