# -*- mode: ansible -*-
- name: Install home-assistant
  hosts: home-assistant
  become: true
  tasks:
    - include_tasks: tasks/magic-sysrq.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/apt_upgrade_from_backports.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/apt_upgrade.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/vars+packages.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/rtl8851bu.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/coral-pcie.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/%sudo.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/autologin.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/remove_ifupdown.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/install_NetworkManager.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/mDNS_by_systemd.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/home-assistant-supervised.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/hotspot-in-spite-of-home-assistant.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/sysctl_settings.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/general.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/barrier.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/kiosk.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/reboot+wait.yml # noqa: fqcn[action-core] name[missing]
