# -*- mode: ansible -*-
- name: Install juntek_monitor
  hosts: rv_ha
  become: true
  tasks:
    - include_tasks: tasks/wifi-powersave-off.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/vars+packages.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/armbianEnv-overlay.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/apt_upgrade.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/threads-max.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/editor.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/mDNS_by_systemd.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/connectivity_check.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/docker-ce.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/install_remote_desktop.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/enable_bluetooth.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/install_juntek_monitor.yml # noqa: fqcn[action-core] name[missing]
    - include_tasks: tasks/generator.yml # noqa: fqcn[action-core] name[missing]
