#!/usr/bin/env bash

while ! ha network update --disabled "{{ wifi_interface }}"; do
	sleep 1
done
[[ "$(nmcli c)" =~ "{{ wifi_ssid }}" ]] ||
nmcli c add con-name "{{ wifi_ssid }}" \
  type wifi \
  ifname "{{ wifi_interface }}" \
  ssid "{{ wifi_ssid }}" \
  autoconnect off \
  ipv4.method shared \
  ipv4.addresses 192.168.42.1/24 \
  802-11-wireless.mode ap \
  802-11-wireless.band bg \
  802-11-wireless.channel 5 \
  wifi-sec.key-mgmt \
  wpa-psk wifi-sec.psk "{{ wifi_psk }}"
nmcli c up "{{ wifi_ssid }}"
