services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    hostname: ccab4aaf-frigate-fa
    dns:
      - 172.30.32.3
    dns_opt:
      - timeout:10
    dns_search:
      - local.hass.io
    extra_hosts:
      hassio: 172.30.32.2
      supervisor: 172.30.32.2
    shm_size: "192mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/hassio/homeassistant:/config
      - /usr/share/hassio/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      CONFIG_FILE: /config/frigate.yml
    expose:
      - "5000/tcp"
      - "8554/tcp"
      - "8555/tcp"
      - "8555/udp"
    ports:
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    networks:
      hassio:
        ipv4_address: 172.30.33.1

networks:
  hassio:
    external: true
