all:
  vars:
    ansible_user: jkt
  children:
    local:
      hosts:
        localhost:
    bare:
      hosts:
        orangepizero2w:
        radxa-zero3:
        rpi4b:
    bt_dev:
      hosts:
        thinny:
          desktop: lxqt
    ha:
      hosts:
        home-assistant:
          desktop: lxqt
    radxa_zero3:
      hosts:
        radxa-zero3:
        jkt-rv-ha:
        jkt-rv:
    rv_ha:
      hosts:
        jkt-rv-ha:
        jkt-rv:
    ha_dev:
      hosts:
        fridge-magnet:
        uefi-x86:
        buildroot:
    play:
      hosts:
        tiny:
    brewing:
      hosts:
        fridge-magnet:
