# -*- mode: ansible -*-
---
- name: Update and upgrade apt packages from backports
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # One day
    default_release: "{{ backports_release | default('bookworm-backports') }}"
    force: true
    state: latest # noqa package-latest
    name: "{{ item }}"
  with_items: "{{ backports_packages }}"
