# -*- mode: ansible -*-
---
- name: Enable autologin for lightdm
  when: '"lightdm" in ansible_facts.packages'
  vars:
    autologin_path: "/etc/lightdm/lightdm.conf.d/autologin.conf"
  block:
    - name: Ensure configuration directory
      ansible.builtin.file:
        path: "{{ autologin_path | dirname }}"
        state: directory
        mode: u=rwx,go=rx
    - name: Enable autologin
      ansible.builtin.copy:
        dest: "{{ autologin_path }}"
        mode: u=rw,go=r
        content: |
          [Seat:*]
          autologin-user={{ ansible_user }}
          autologin-user-timeout=0
- name: Enable autologin for sddm
  when: '"sddm" in ansible_facts.packages'
  vars:
    autologin_path: "/etc/sddm.conf.d/autologin.conf"
  block:
    - name: Ensure configuration directory
      ansible.builtin.file:
        path: "{{ autologin_path | dirname }}"
        state: directory
        mode: u=rwx,go=rx
    - name: Enable autologin
      ansible.builtin.copy:
        dest: "{{ autologin_path }}"
        mode: u=rw,go=r
        content: |
          [Autologin]
          User={{ ansible_user }}
          Session={{ desktop | default('plasma') }}
