# -*- mode: ansible -*-
---
- include_tasks: tasks/gawk.yml # noqa: fqcn[action-core] name[missing]
- name: Ensure bin directory
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: u=rwx,go=rx
- name: Install duckdns
  ansible.builtin.copy:
    dest: /usr/local/bin/duckdns
    mode: u=rwx,go=rx
    content: |
      #!/usr/bin/env bash
      curl -s "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip={{ duckdns_ip | default('') }}"
      ip6=$(nmcli c show 'Supervisor enp3s0' | gawk '/IP6.ADDRESS.1]:/{ print gensub("/.*", "", "1", $2) }') && \
      curl -s "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ipv6=$ip6"
- name: Install cron job
  ansible.builtin.cron:
    name: duckdns
    minute: 11
    hour: 0
    job: /usr/local/bin/duckdns
    user: "{{ ansible_user }}"
