# -*- mode: ansible -*-
---
- include_tasks: tasks/install_packages.yml # noqa: fqcn[action-core] name[missing]
  vars:
    packages:
      - rfkill
- name: Fix ConfigurationDirectoryMode
  ansible.builtin.file:
    path: /etc/bluetooth
    state: directory
    mode: ugo=rx
- name: Enable bluetooth device
  ansible.builtin.include_tasks: tasks/systemd-drop-in.yml
  vars:
    service: bluetooth.service
    content: |
      [Unit]
      Description=+reset hardware
      [Service]
      ExecStartPost=-rfkill unblock bluetooth
      ExecStartPost=-hciattach -s 1500000 /dev/ttyS1 any 1500000 flow nosleep
      ExecStartPost=-hciconfig hci0 up
- name: Restart bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    state: restarted
  when: systemd_drop_in.changed # noqa: no-handler
