# -*- mode: ansible -*-
---
- name: Require reboot
  ansible.builtin.file:
    path: /var/run/reboot-required
    mode: u=r,go=
    state: touch
- include_tasks: tasks/reboot+wait.yml # noqa: fqcn[action-core] name[missing]
