# -*- mode: ansible -*-
# frigate-nvr records cameras and detects motion
---
- name: Create supervisor control script
  ansible.builtin.template:
    src: files/mnt/data/supervisor/addon_configs/ccab4aaf_frigate-fa/config.yml
    dest: /mnt/data/supervisor/addon_configs/ccab4aaf_frigate-fa/config.yml
    mode: u=rw,go=
