# -*- mode: ansible -*-
---
# color me old fashioned
- name: Purge mawk
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  with_items:
    - mawk
  when: item in ansible_facts.packages
- name: Install gawk
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - gawk
  when: item not in ansible_facts.packages
