# -*- mode: ansible -*-
---
- name: Remove xscreensaver
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - xscreensaver
  when: item in ansible_facts.packages
- name: Install kiosk
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - chromium
    - sysstat
    - unclutter
  when: item not in ansible_facts.packages
- name: Configure kiosk
  ansible.builtin.unarchive:
    src: files/kiosk.tar.gz
    dest: "/home/{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    creates: "/home/{{ ansible_user }}/bin/kiosk_check"
- name: Check kiosk
  ansible.builtin.cron:
    name: kiosk_check
    minute: "*"
    job: /home/{{ ansible_user }}/bin/kiosk_check
    user: "{{ ansible_user }}"
- name: Add to Desktop
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/.config/autostart/kiosk.desktop"
    dest: "/home/{{ ansible_user }}/Desktop/kiosk.desktop"
    owner: "{{ ansible_user }}"
    mode: ug=rw,o=r
    state: hard
    force: true
