# -*- mode: ansible -*-
---
- name: Switch NetworkManager to systemd-resolved
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/dns.conf
    mode: u=rw,go=r
    content: |
      [main]
      dns=systemd-resolved
- name: Enable mDNS on network connections
  ansible.builtin.shell: |
    set -o pipefail
    nmcli -t -f UUID,TYPE c | awk -F: '/802-/{system("nmcli c modify " $1 " connection.mdns yes")}'
  args:
    executable: /bin/bash
  register: mdns
  changed_when: mdns.rc == 0
- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
