# -*- mode: ansible -*-
---
- name: Install multicast service
  ansible.builtin.copy:
    dest: /etc/systemd/system/mDNS@.service
    mode: u=rw,go=r
    content: |
      [Unit]
      Description=Enable mDNS on interface
      After=systemd-resolved.service
      [Service]
      Type=oneshot
      ExecStart=resolvectl mdns %i yes
      [Install]
      WantedBy=multi-user.target
- name: Enable mDNS on network connections
  ansible.builtin.shell: |
    set -o pipefail
    ip a | awk -F': ' '$2 ~ /^[ew]/{system("systemctl enable --now mDNS@" $2)}'
  args:
    executable: /bin/bash
  register: mdns
  changed_when: mdns.rc == 0
