# -*- mode: ansible -*-
---
- name: Switch NetworkManager to systemd-resolved
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/dns.conf
    mode: u=rw,go=r
    content: |
      [main]
      dns=systemd-resolved
  register: dns
- name: Enable mDNS on network connections
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/mDNS.conf
    mode: u=rw,go=r
    content: |
      [connection]
      mdns=2
      llmnr=0
  register: mdns
- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  when: dns.changed or mdns.changed # noqa: no-handler
