# -*- mode: ansible -*-
---
- name: Purge netplan
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  with_items:
    - netplan.io
    - libnetplan0
  when: item in ansible_facts.packages
- name: Cleanup netplan
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/netplan
    - /usr/share/netplan
