# -*- mode: ansible -*-
---
- name: Install dkms and git
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - dkms
    - git
  when: item not in ansible_facts.packages
- name: Check if RTL8851bu is already installed
  ansible.builtin.command: dkms status -m rtl8851bu
  register: rtl8851bu
  failed_when: rtl8851bu.rc != 0
  changed_when: false
- name: Clone RTL8831
  ansible.builtin.git:
    repo: https://github.com/biglinux/RTL8831.git
    dest: /tmp/RTL8831
    version: main
  when: '"installed" not in rtl8851bu.stdout'
- name: Install rtl8831
  ansible.builtin.command:
    chdir: /tmp/RTL8831
    cmd: dkms install .
  when: '"installed" not in rtl8851bu.stdout'
  changed_when: true
- name: Request reboot
  ansible.builtin.file:
    path: /var/run/reboot-required
    mode: u=r,go=
    state: touch
  when: '"installed" not in rtl8851bu.stdout'
- include_tasks: tasks/reboot+wait.yml # noqa: fqcn[action-core] name[missing]
  when: '"installed" not in rtl8851bu.stdout'
