# -*- mode: ansible -*-
# Create a systemd drop-in file for a service named by the first word of Description.
# WARNING: Description MUST be unique and SHOULD be simple.
# vars:
#   service: foo.service
#   content: |
#     [Unit]
#     Description=Foo
#     After=bar.service
# creates /etc/systemd/system/foo.service.d/Description.conf
---
- name: Create systemd drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/system/{{ service }}.d
    state: directory
    mode: u=rwx,go=rx
- name: Create systemd drop-in file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ service }}.d/{{ content | regex_search('Description=\\S+', multiline=true) | regex_replace('.*=', '') }}.conf"
    mode: u=rw,go=r
    content: "{{ content }}"
  register: systemd_drop_in
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_drop_in.changed # noqa: no-handler
