# -*- mode: ansible-jinja -*-
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    cap_add:
      - CAP_PERFMON
      - SYS_ADMIN # required for GPU support
    devices:
      - /dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/{{ ansible_user }}/frigate:/config
      - /mnt/data/supervisor/media/frigate:/media/frigate
      - type: tmpfs # 1GB In-memory filesystem for recording segment storage
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host
{% if inventory_hostname == 'thinny' %}
    environment:
      LIBVA_DRIVER_NAME: radeonsi
{% endif %}
