# -*- mode: ansible-jinja -*-
cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - detect
            - record
    motion:
      mask: 0,0.529,0.343,0.136,1,0.126,1,0,0,0
      threshold: 30
      contour_area: 25
      improve_contrast: 'true'
    zones:
      Front_Person_Detection:
        coordinates: 0.291,0.207,0,0.568,0,1,1,1
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: Front_Person_Detection
      detections:
        required_zones: Front_Person_Detection
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
            - record
    zones:
      driveway_detection_zone:
        coordinates: 0.202,0.217,0.998,0.337,0.997,0.663,0.108,0.704
        loitering_time: 0
        friendly_name: Driveway_Detection_Zone
    review:
      alerts:
        required_zones: driveway_detection_zone
      detections:
        required_zones: driveway_detection_zone
  back:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          roles:
            - detect
            - record
    motion:
      mask: 0,1,0.194,0.998,0.414,0.589,0.349,0,0,0
    zones:
      back_detection_zone:
        coordinates: 0.353,0.002,0.739,-0.002,0.997,0.408,1,1,0.445,1
        loitering_time: 0
        friendly_name: Back_Detection_Zone
    review:
      alerts:
        required_zones: back_detection_zone
      detections:
        required_zones: back_detection_zone

{% if inventory_hostname != 'thinny' %}
detect:
  enabled: true
  width: 2560
  height: 1440

detectors:
  ov_0:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
{% endif %}

ffmpeg:
{% if inventory_hostname == 'thinny' %}
  hwaccel_args: preset-vaapi
{% else %}
  hwaccel_args: preset-intel-qsv-h264
{% endif %}
  input_args: preset-rtsp-restream

go2rtc:
  streams:
    front:
      # 60:83:E7:C3:3B:DC
      - rtsp://tp-link-tapo@jkth628.fastmail.us:{{ front_password }}@192.168.11.251:554/{{ camera_quality | default('stream1') }}
      - ffmpeg:front#hardware
    driveway:
      # 60:83:E7:C3:38:AC
      - rtsp://tp-link-tapo@jkth628.fastmail.us:{{ driveway_password }}@192.168.11.252:554/{{ camera_quality | default('stream1') }}
      - ffmpeg:driveway#hardware
    back:
      # 60:83:E7:C3:39:07
      - rtsp://tp-link-tapo@jkth628.fastmail.us:{{ back_password }}@192.168.11.253:554/{{ camera_quality | default('stream1') }}
      - ffmpeg:back#hardware

mqtt:
  enabled: true
  host: "{{ haos.HOST }}.local"
  user: frigate-nvr
  password: "{{ frigate_nvr_password }}"

objects:
  track:
    - person
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 45000

record:
  enabled: true
  sync_recordings: true
  alerts:
    retain:
      days: 60
  detections:
    retain:
      days: 60
  continuous:
    days: 14
  motion:
    days: 14
version: 0.17-0
